var adjectives = [
  'adamant',
  'adroit',
  'amatory',
  'animistic',
  'antic',
  'arcadian',
  'baleful',
  'bellicose',
  'bilious',
  'boorish',
  'calamitous',
  'caustic',
  'cerulean',
  'comely',
  'concomitant',
  'contumacious',
  'corpulent',
  'crapulous',
  'defamatory',
  'didactic',
  'dilatory',
  'dowdy',
  'efficacious',
  'effulgent',
  'egregious',
  'endemic',
  'equanimous',
  'execrable',
  'fastidious',
  'feckless',
  'fecund',
  'friable',
  'fulsome',
  'garrulous',
  'guileless',
  'gustatory',
  'heuristic',
  'histrionic',
  'hubristic',
  'incendiary',
  'insidious',
  'insolent',
  'intransigent',
  'inveterate',
  'invidious',
  'irksome',
  'jejune',
  'jocular',
  'judicious',
  'lachrymose',
  'limpid',
  'loquacious',
  'luminous',
  'mannered',
  'mendacious',
  'meretricious',
  'minatory',
  'mordant',
  'munificent',
  'nefarious',
  'noxious',
  'obtuse',
  'parsimonious',
  'pendulous',
  'pernicious',
  'pervasive',
  'petulant',
  'platitudinous',
  'precipitate',
  'propitious',
  'puckish',
  'querulous',
  'quiescent',
  'rebarbative',
  'recalcitant',
  'redolent',
  'rhadamanthine',
  'risible',
  'ruminative',
  'sagacious',
  'salubrious',
  'sartorial',
  'sclerotic',
  'serpentine',
  'spasmodic',
  'strident',
  'taciturn',
  'tenacious',
  'tremulous',
  'trenchant',
  'turbulent',
  'turgid',
  'ubiquitous',
  'uxorious',
  'verdant',
  'voluble',
  'voracious',
  'wheedling',
  'withering',
  'zealous'
]
var nouns = [
  'ninja',
  'chair',
  'pancake',
  'statue',
  'unicorn',
  'rainbows',
  'laser',
  'senor',
  'bunny',
  'captain',
  'nibblets',
  'cupcake',
  'carrot',
  'gnomes',
  'glitter',
  'potato',
  'salad',
  'toejam',
  'curtains',
  'beets',
  'toilet',
  'exorcism',
  'stick figures',
  'mermaid eggs',
  'sea barnacles',
  'dragons',
  'jellybeans',
  'snakes',
  'dolls',
  'bushes',
  'cookies',
  'apples',
  'ice cream',
  'ukulele',
  'kazoo',
  'banjo',
  'opera singer',
  'circus',
  'trampoline',
  'carousel',
  'carnival',
  'locomotive',
  'hot air balloon',
  'praying mantis',
  'animator',
  'artisan',
  'artist',
  'colorist',
  'inker',
  'coppersmith',
  'director',
  'designer',
  'flatter',
  'stylist',
  'leadman',
  'limner',
  'make-up artist',
  'model',
  'musician',
  'penciller',
  'producer',
  'scenographer',
  'set decorator',
  'silversmith',
  'teacher',
  'auto mechanic',
  'beader',
  'bobbin boy',
  'clerk of the chapel',
  'filling station attendant',
  'foreman',
  'maintenance engineering',
  'mechanic',
  'miller',
  'moldmaker',
  'panel beater',
  'patternmaker',
  'plant operator',
  'plumber',
  'sawfiler',
  'shop foreman',
  'soaper',
  'stationary engineer',
  'wheelwright',
  'woodworkers'
]
var cities = [
  { name: 'Bedford, OH', path: { lat: 41.392502, lng: -81.534447 } },
  { name: 'Stuart, FL', path: { lat: 27.192223, lng: -80.243057 } },
  { name: 'San Angelo, TX', path: { lat: 31.442778, lng: -100.450279 } },
  { name: 'Woodbridge, NJ', path: { lat: 40.560001, lng: -74.290001 } },
  { name: 'Clinton, MI', path: { lat: 42.586945, lng: -82.919998 } },
  { name: 'Vista, CA', path: { lat: 33.193611, lng: -117.241112 } },
  { name: 'South Bend, IN', path: { lat: 41.676388, lng: -86.250275 } },
  { name: 'Davenport, IA', path: { lat: 41.543056, lng: -90.590836 } },
  { name: 'Sparks, NV', path: { lat: 39.554443, lng: -119.735558 } },
  { name: 'Green Bay, WI', path: { lat: 44.513332, lng: -88.015831 } },
  { name: 'San Mateo, CA', path: { lat: 37.554169, lng: -122.313057 } },
  { name: 'Tyler, TX', path: { lat: 32.349998, lng: -95.300003 } },
  { name: 'League City, TX', path: { lat: 29.499722, lng: -95.089722 } },
  { name: 'Lewisville, TX', path: { lat: 33.038334, lng: -97.006111 } },
  { name: 'Meridian, ID', path: { lat: 43.614166, lng: -116.398888 } },
  { name: 'Waterbury, CT', path: { lat: 41.55611, lng: -73.041389 } },
  { name: 'Jurupa Valley, CA', path: { lat: 34.0, lng: -117.48333 } },
  { name: 'West Palm Beach, FL', path: { lat: 26.709723, lng: -80.064163 } },
  { name: 'Antioch, CA', path: { lat: 38.005001, lng: -121.805832 } },
  { name: 'High Point, NC', path: { lat: 35.970554, lng: -79.997498 } },
  { name: 'Miami Gardens, FL', path: { lat: 25.942122, lng: -80.26992 } },
  { name: 'Murrieta, CA', path: { lat: 33.569443, lng: -117.202499 } },
  { name: 'Springfield, IL', path: { lat: 39.799999, lng: -89.650002 } },
  { name: 'El Monte, CA', path: { lat: 34.073334, lng: -118.027496 } },
  { name: 'West Jordan, UT', path: { lat: 40.606388, lng: -111.976112 } },
  { name: 'College Station, TX', path: { lat: 30.601389, lng: -96.314445 } },
  { name: 'Fairfield, CA', path: { lat: 38.257778, lng: -122.054169 } },
  { name: 'Evansville, IN', path: { lat: 37.977222, lng: -87.550552 } },
  { name: 'Cambridge, MA', path: { lat: 42.373611, lng: -71.110558 } },
  { name: 'Kansas City, KS', path: { lat: 39.106667, lng: -94.676392 } },
  { name: 'Springfield, MA', path: { lat: 42.101391, lng: -72.590279 } }
]

module.exports = {
  adjectives,
  nouns,
  cities
}
